Repository cse110-sp24-group7/warmup-exercise, pull requests merged in 2024-04, with the labels that each got.

#9 widget/naina+mialyssa/semicircle
  gradient-widget/gradient-widget-docs.md
  gradient-widget/rectangle_gradient.html
  gradient-widget/semicircle-progress/scratchwork.html
  gradient-widget/semicircle-progress/semi_circle.html
Labels: MVP

#12 Yelp Review Component Merge Request
  review/review.css
  review/review.html
  review/review.js
Labels: enhancement

#17 Docs/arnav+samvrit/documentation+yaml
  .github/workflows/pr.yaml
  .github/workflows/random-review.yaml
  .github/workflows/testing.yml
Labels: documentation

#18 Integration of Gradient and Form
  gradient-widget-rectangle/background.js
  integration/index.html
  integration/scripts/background.js
  integration/style/gradient.css
Labels: enhancement, help wanted, MVP, Integration

#19 Instruction Pop up and Logo
  info-tab.md
  integration/index.html
  integration/style/gradient.css
Labels: documentation, enhancement, Integration
